name: praktikum_statemachine_dan_testing
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  http: ^0.13.5

  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
