// Mocks generated by Mockito 5.4.0 from annotations
// in praktikum_statemachine_dan_testing/test/model/api/food_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:praktikum_statemachine_dan_testing/api/food_api.dart' as _i3;
import 'package:praktikum_statemachine_dan_testing/model/food_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodModel_0 extends _i1.SmartFake implements _i2.FoodModel {
  _FakeFoodModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiFood].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiFood extends _i1.Mock implements _i3.ApiFood {
  MockApiFood() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.FoodModel>> getFoods() => (super.noSuchMethod(
        Invocation.method(
          #getFoods,
          [],
        ),
        returnValue: _i4.Future<List<_i2.FoodModel>>.value(<_i2.FoodModel>[]),
      ) as _i4.Future<List<_i2.FoodModel>>);
}
