name: praktikum_section_21
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_colorpicker: ^1.0.3
  file_picker: ^4.3.3
  open_file: ^3.2.1
  navbar_router: ^0.4.2
  provider: ^6.0.5
  page_transition: ^2.0.9
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
